Fix TypeError: decode_bytes() missing 1 required positional argument 'mode' (#256)
* Fix TypeError: decode_bytes() missing 1 required positional argument: 'mode'

Update decode_bytes call to include mode parameter.

* simple checks for the main formatting functions used by the cli

* use a more modern version of the utc datetime functions

* backwards compat

* changelog

---------

Co-authored-by: Justus Magin <keewis@posteo.de>